language: java
sudo: false # faster builds

jdk:
  - oraclejdk8

install: true

script:
  - ./mvnw clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2

services:
  - redis-server
